WIP: Add AdvancedSelect component
pynecone-io/pynecone pull request #1043
Opened 2023-05-17 19:49 UTC by iron3oxide

### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

Adds AdvancedSelect and AdvancedOption, which in tandem would enable stuff like searchable/ editable selects and MultiSelects. Wraps the `chakra-react-select` library.

Doesn't really work yet, I'm probably doing something wrong.

2023-05-17 19:52 UTC, iron3oxide commented
This is the error message I'm usually getting:

```bash
poetry run pc run
───────────────────────── Starting Pynecone App ─────────────────────────
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/PycharmProjects/pynecone/pynecone/pc.py", line 114, in run
    app = prerequisites.get_app()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/PycharmProjects/pynecone/pynecone/utils/prerequisites.py", line 104, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/PycharmProjects/pynecone/examples/example/example/example.py", line 42, in <module>
    app.add_page(index)
  File "/home/jason/PycharmProjects/pynecone/pynecone/app.py", line 270, in add_page
    raise e
  File "/home/jason/PycharmProjects/pynecone/pynecone/app.py", line 261, in add_page
    component = component if isinstance(component, Component) else component()
                                                                   ^^^^^^^^^^^
  File "/home/jason/PycharmProjects/pynecone/examples/example/example/example.py", line 35, in index
    pc.aselect([3, 2]),
    ^^^^^^^^^^^^^^^^^^
  File "/home/jason/PycharmProjects/pynecone/pynecone/components/forms/advanced_select.py", line 350, in create
    return super().create(*[], **props)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/PycharmProjects/pynecone/pynecone/components/component.py", line 368, in create
    return cls(children=children, **props)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/PycharmProjects/pynecone/pynecone/components/component.py", line 138, in __init__
    f"Invalid var passed for prop {key}, expected type {expected_type}, got value {value} of type {passed_type}."
  File "/home/jason/PycharmProjects/pynecone/pynecone/components/component.py", line 291, in __repr__
    return format.json_dumps(self.render())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/PycharmProjects/pynecone/pynecone/utils/format.py", line 423, in json_dumps
    return json.dumps(obj, ensure_ascii=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```

2023-05-17 22:09 UTC, ElijahAhianyo commented
> This is the error message I'm usually getting:
> 
> ```shell
> poetry run pc run
> ───────────────────────── Starting Pynecone App ─────────────────────────
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
>     return get_command(self)(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/.cache/pypoetry/virtualenvs/pynecone-Yp1zm8LS-py3.11/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
>     return callback(**use_params)  # type: ignore
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/PycharmProjects/pynecone/pynecone/pc.py", line 114, in run
>     app = prerequisites.get_app()
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/PycharmProjects/pynecone/pynecone/utils/prerequisites.py", line 104, in get_app
>     return __import__(module, fromlist=(constants.APP_VAR,))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/PycharmProjects/pynecone/examples/example/example/example.py", line 42, in <module>
>     app.add_page(index)
>   File "/home/jason/PycharmProjects/pynecone/pynecone/app.py", line 270, in add_page
>     raise e
>   File "/home/jason/PycharmProjects/pynecone/pynecone/app.py", line 261, in add_page
>     component = component if isinstance(component, Component) else component()
>                                                                    ^^^^^^^^^^^
>   File "/home/jason/PycharmProjects/pynecone/examples/example/example/example.py", line 35, in index
>     pc.aselect([3, 2]),
>     ^^^^^^^^^^^^^^^^^^
>   File "/home/jason/PycharmProjects/pynecone/pynecone/components/forms/advanced_select.py", line 350, in create
>     return super().create(*[], **props)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/PycharmProjects/pynecone/pynecone/components/component.py", line 368, in create
>     return cls(children=children, **props)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/PycharmProjects/pynecone/pynecone/components/component.py", line 138, in __init__
>     f"Invalid var passed for prop {key}, expected type {expected_type}, got value {value} of type {passed_type}."
>   File "/home/jason/PycharmProjects/pynecone/pynecone/components/component.py", line 291, in __repr__
>     return format.json_dumps(self.render())
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jason/PycharmProjects/pynecone/pynecone/utils/format.py", line 423, in json_dumps
>     return json.dumps(obj, ensure_ascii=False)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
>     **kw).encode(obj)
>           ^^^^^^^^^^^
>   File "/usr/lib64/python3.11/json/encoder.py", line 200, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/json/encoder.py", line 258, in iterencode
>     return _iterencode(o, 0)
>            ^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/json/encoder.py", line 180, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type set is not JSON serializable
> ```

There's no support for sets in json, so sets need to converted to lists in this case. May not be the cleanest solution but if you change the json dumps line in format.py to `json.dumps(obj, ensure_ascii=False, default=list)` that should work.

2023-05-18 01:41 UTC, picklelo reviewed
Great work! Wasn't sure how to add to this so I opened a new branch with some fixes that make it work: #1044

You can base your PR on that - once this is cleaned up I'm thinking we make this the default `pc.select` component since it's much better than the current one.

2023-05-18 01:41 UTC, picklelo commented on pynecone/components/forms/advanced_select.py
> +    label: Var[str]
For non-components we don't need to use `Var`

2023-05-18 01:41 UTC, picklelo commented on pynecone/components/forms/advanced_select.py
> +    def create(cls, label: str, **props) -> Component:
Then we can move this logic to the `__init__` function for non-components

2023-05-18 01:41 UTC, picklelo commented on pynecone/components/forms/advanced_select.py
> +                checked_options.append(AdvancedOption.create(label=str(option)))
Looks like the `options` prop expects a list of dicts which his the main problem

2023-05-23 19:04 UTC, picklelo requested changes
Thanks for adding this, this is a huge improvement over the default one. Just a couple typing issues to get the build passing for Python < 3.9 and then we can merge this

2023-05-23 19:04 UTC, picklelo commented on pynecone/components/forms/select.py
> +    components: Var[dict[str, Component]]
This needs to be `Dict[str, Component]` to support Python < 3.9

2023-05-23 19:04 UTC, picklelo commented on pynecone/components/forms/select.py
> +    options: Var[list[Dict]]
This needs to be `List[Dict]`

2023-05-23 19:04 UTC, picklelo commented on pynecone/components/forms/select.py
> +        cls, options: List[Option | str | int | float | bool], **props
We need to use `List[Union[Option, str, int, float, bool]]`

2023-05-24 11:03 UTC, iron3oxide commented
done

2023-05-24 19:42 UTC, picklelo approved these changes
awesome!

2023-05-24 20:19 UTC, merged

2023-05-28 16:48 UTC, masenf commented
is there a doc update planned for this? seems like https://pynecone.io/docs/library/forms/select has bad information now.