Add option to specify port
pynecone-io/pynecone pull request #192
Opened 2022-12-30 06:36 UTC by pysqz

fix issue [#157](https://github.com/pynecone-io/pynecone/issues/157)

2022-12-30 07:59 UTC, picklelo requested changes
Thanks for making this change!

2022-12-30 07:59 UTC, picklelo commented on pynecone/utils.py
> +def get_api_port():
This needs a return type annotation `-> str` as well as a doctoring to make the build happy

2022-12-30 07:59 UTC, picklelo commented on pynecone/utils.py
> +        return urlparse(constants.API_URL).port
You may need to add an assert here for Pyright
```
port = urlparse(...)
assert port is not None
return port
```

2022-12-30 07:59 UTC, picklelo commented on pynecone/utils.py
> +        "0.0.0.0:%s"%get_api_port(),
Can we use an f-string here for consistency with the rest of the code?

2022-12-30 08:14 UTC, Alek99 commented
Yes thanks for implementing this feature defiantly needed! 🙂

2022-12-30 09:02 UTC, pysqz commented
update the commit, pls review again~ @picklelo @Alek99

2022-12-30 18:03 UTC, picklelo approved these changes
Looks good to me - it just needs to be linted. You can run
```
poetry run black pynecone
```
and it should format the code for you, then we can merge this

2022-12-31 12:51 UTC, pysqz commented
> Looks good to me - it just needs to be linted. You can run
> 
> ```
> poetry run black pynecone
> ```
> 
> and it should format the code for you, then we can merge this

done

2022-12-31 17:41 UTC, merged