Empty .web/pages directory on recompile
pynecone-io/pynecone pull request #269
Opened 2023-01-16 20:32 UTC by andy-verstraeten

Empty the .web/pages directory on recompile so that old pages that don't exist anymore in the python code get removed.

2023-01-16 22:34 UTC, picklelo requested changes
Thanks for digging into this!

2023-01-16 22:34 UTC, picklelo commented on pynecone/compiler/compiler.py
> +    utils.empty_dir(constants.WEB_PAGES_DIR)
There's two special files in the pages directory - `._app.js` and `404.js` that are part of the template and not recompiled. I think we need to exclude those two files when purging the dir.

2023-01-17 10:35 UTC, andy-verstraeten commented
Both files were added to an ignore list.

2023-01-17 16:45 UTC, picklelo commented on pynecone/compiler/compiler.py
> +    template_files = ["_app.js","404.js"]
I think you forgot to pass this in as an argument

2023-01-17 16:45 UTC, picklelo commented on pynecone/compiler/utils.py
> +    print(directory_contents)
We can remove this print

2023-01-17 20:49 UTC, andy-verstraeten commented
My bad.

2023-01-17 22:46 UTC, picklelo approved these changes
Awesome!

2023-01-17 22:51 UTC, picklelo commented
Sorry, needs one more change to make the linter happy (I think it wants the docstring on a single line). Can you make sure the following checks pass:
```
poetry run pyright pynecone tests
poetry run pydocstyle pynecone tests
find pynecone tests -name "*.py" -not -path pynecone/pc.py | xargs poetry run darglint
poetry run black pynecone tests
```

2023-01-18 20:10 UTC, picklelo commented
Thank you for the persistence 😄

2023-01-18 20:11 UTC, merged