Check if curl and unzip are installed, fix #383
pynecone-io/pynecone pull request #386
Opened 2023-01-29 18:28 UTC by HellAmbro

As @brianmcconnel noted, Pynecone initialization may fail if curl and unzip are not installed.
Checks whether they are installed, if not the user is notified with a proper message.

2023-01-29 23:42 UTC, picklelo approved these changes
Thanks for adding

2023-01-29 23:44 UTC, picklelo requested changes
Just one change to make the linter happy

2023-01-29 23:44 UTC, picklelo commented on pynecone/utils.py
> +            raise FileNotFoundError("Pynecone requires curl to be installed.")
We need to add this to the docstring:
```
"""Install bun onto the user's system.

Raises:
    FileNotFoundError: If the required packages are not installed.
"""
```

2023-01-30 09:24 UTC, HellAmbro commented on pynecone/utils.py
> +            raise FileNotFoundError("Pynecone requires curl to be installed.")
Done.

2023-01-30 20:10 UTC, picklelo approved these changes
Awesome

2023-01-30 20:13 UTC, merged