Fix bug on setting plotly figure as State.vars
pynecone-io/pynecone pull request #440
Opened 2023-02-04 11:13 UTC by lawrence-axb

### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.
Fix bug on setting plotly figure as State.vars
    b. Describe your changes.
plotly.figure was not accepted even the TypeError said that Plotly figures is acceptable
    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2023-02-04 18:56 UTC, picklelo approved these changes
Sweet thanks for this

2023-02-04 18:57 UTC, picklelo requested changes
Looks like this needs to be ilnted with `black`

2023-02-05 00:00 UTC, lawrence-axb commented
@picklelo Thanks! I missed it :D

2023-02-05 00:10 UTC, picklelo approved these changes

2023-02-05 00:10 UTC, picklelo commented on CONTRIBUTING.md
> +poetry run black pynecone tests
thanks for adding!

2023-02-05 00:13 UTC, merged