Added KeyboardKey, AspectRatio Components
pynecone-io/pynecone pull request #685
Opened 2023-03-15 09:29 UTC by HellAmbro

### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

2023-03-15 09:34 UTC, HellAmbro commented
Reference:
https://v1.chakra-ui.com/docs/components/other/show-hide
https://v1.chakra-ui.com/docs/components/data-display/kbd
https://v1.chakra-ui.com/docs/components/layout/aspect-ratio

2023-03-16 05:37 UTC, Alek99 requested changes

2023-03-16 05:37 UTC, Alek99 commented on pynecone/components/other/show_hide.py
For show/hide do you think we need this because our  responsive styling achieves this functionality already? As well as pc.cond can show/hide based on a boolean in the state.

https://pynecone.io/docs/styling/responsive

2023-03-16 05:37 UTC, Alek99 commented on pynecone/components/layout/aspect_ratio.py
Nice feature to add!

2023-03-17 08:55 UTC, HellAmbro commented on pynecone/components/other/show_hide.py
Thanks, I'll fix it

2023-03-17 22:13 UTC, Alek99 approved these changes
lgtm

2023-03-17 22:15 UTC, merged