Added html component
pynecone-io/pynecone pull request #98
Opened 2022-12-14 23:31 UTC by Alek99

2022-12-14 23:46 UTC, picklelo requested changes
Sweet! Just a couple nits

2022-12-14 23:46 UTC, picklelo commented on pynecone/components/layout/box.py
> +        Returns:
Update this docstring

2022-12-14 23:46 UTC, picklelo commented on pynecone/components/layout/box.py
> +        Raises:
And here also

2022-12-14 23:46 UTC, picklelo commented on pynecone/components/layout/box.py
> +class Html(Box):
Let's separate this out to its own file

2022-12-14 23:59 UTC, FHU-yezi commented
> Sweet! Just a couple nits

But the reward is not just a bit :sweet:

2022-12-15 00:12 UTC, picklelo approved these changes
Nice work

2022-12-15 00:13 UTC, merged